### ISSUE TITLE
download source code

### ISSUE THREAD

**Issue by xvtstephen** [ehassler/MontgomeryDAE#3]
This is not an issue, but a request. Can you make the files at https://rdrr.io/github/ehassler/MontgomeryDAE/f/
available in a zip or tar.gz or just put all code in a single file?
Thanks
Stephen

**Comment by ehassler** [comment]
Hi Stephen, 
I think rdrr.io is an external entity, but you can grab the release archive here on GitHub to get all of the files.  Right now the current release is [https://github.com/ehassler/MontgomeryDAE/releases/download/10.1/MontgomeryDAE_10.1.tar.gz](https://github.com/ehassler/MontgomeryDAE/releases/download/10.1/MontgomeryDAE_10.1.tar.gz).

**Comment by xvtstephen** [comment]
I installed as per instruction in Readme and the R files were not
installed. the tar.gz had a /doc folder which contains the .R files.
just a suggestion: can you make the install such that the /doc folder
will install?
Cheers
